/*
 *  MessageFacility.idl
 *  ==================================================================
 *  
 *  Defination of OpenSplice DDS IDL data type for logging messages
 *  with MessageFacility over networks.
 *
 *  qlu  02/11/10    Created
 *  qlu  03/02/10    Added hostname_, hostaddr_, pid_ to MFMessage.
 *                   Keylist has been changed to pid_ and hostname_
 *
 */

module MessageFacility {

    struct MFMessage {
        long      serial_;          // serial
        string    timestamp_;       // timestamp

        string    items_;           // a combined string for all items

        string    file_;             // filename
        string    line_;             // line number

        string    process_;         // process name
        long      pid_;             // process id

        string    id_;              // message_id, or the category
        string    idOverflow_;      // the overflow part of the message id

        string    severity_;        // string represent of severity
        string    module_;          // module name
        string    context_;         // context
        string    subroutine_;      // subroutine name

        string    hostname_;        // host name
        string    hostaddr_;        // host ip address
    };
    #pragma keylist MFMessage pid_ hostname_

};
